### ISSUE TITLE
Текущий статус

### ISSUE THREAD

**Issue by gagarski** [KolpakovaAnastasia/TransposeMatrix#1]
Код выглядит неплохо, но программа не работает (создаётся reader и writer и ничего с ними не делается). Замечания по коду, если будут, то не очень критичные. Дайте пожалуйста отмашку, когда можно бдует смотреть готовую программу. Хотелось бы также обсудить код очно на занятии (а то я вас толком на занятиях не видел и ничего о вас не знаю)

**Comment by KolpakovaAnastasia** [comment]
Даю отмашку

**Comment by gagarski** [comment]
1. Форматирование в Transposition
2. Удалите `ParserTest`, если он не нужен.

**Comment by KolpakovaAnastasia** [comment]
сделано

**Comment by KolpakovaAnastasia** [comment]
все-таки можно будет прийти на экзамен? 21 или 22, например

**Comment by KolpakovaAnastasia** [comment]
И можно будет теперь прийти на экзамен 21 или 22 хотя бы?  А то все экзамены уже сданы на 4 и 5, столько волнения, очень грустно будет ждать еще неделю. Хочется выдохнуть,  если честно

**Comment by gagarski** [comment]
Решение этого задания зафиксировано в текущем состоянии, изменения проверяться не будут.
